CARDS = [
    {'name': 'Start',            'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': 'Otrzymujesz dodatkowe 400$ po przejściu przez to pole!', 'image': 'START'},
    {'name': 'Load balance 1',   'color': 'yellow',     'price': 260, 'type': 'property', 'fee': [26, 78, 156, 234]},
    {'name': 'Płany parking',    'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'PARKING_PAY'},
    {'name': 'Load balance 2',   'color': 'yellow',     'price': 260, 'type': 'property', 'fee': [26, 78, 156, 234]},
    {'name': 'Szansa',           'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'MYSTERY_BLUE'},
    {'name': 'Server 2003',      'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'HOUSE0'},
    {'name': 'Server 2019',      'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': 'Server 2025',      'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': 'Więzienie',        'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': 'Więzienie', 'image': 'JAIL'},
    {'name': 'HTML',             'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': 'CSS',              'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': 'Szansa',           'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'MYSTERY_RED'},
    {'name': 'JavaScript',       'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'HOUSE0'},
    {'name': 'Docker',           'color': 'orange',     'price': 200, 'type': 'property', 'fee': [20, 60, 120, 180]},
    {'name': 'Kubernetes',       'color': 'orange',     'price': 200, 'type': 'property', 'fee': [20, 60, 120, 180]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'HOUSE0'},
    {'name': 'Darmowy parking',  'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': 'Darmowy praking', 'image': 'PARKING'},
    {'name': 'MYSQL',            'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': 'Szansa',           'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'MYSTERY_BLUE'},
    {'name': 'POSTGRESQL',       'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': 'Access',           'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': 'Firewall',         'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': 'Szansa',           'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'MYSTERY_RED'},
    {'name': 'VPN',              'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': 'SSL TLS',          'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': 'Idziesz do więzienia', 'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': 'Idziesz do więzienia, tracisz 2 nastepne tury!', 'image': 'POLICE'},
    {'name': 'IPv4',             'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'HOUSE0'},
    {'name': 'IPv6',             'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': 'DNS',              'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': 'Szansa',           'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'MYSTERY_BLUE'},
    {'name': '',                 'color': '#F7F7F7',    'price': 0,   'type': 'special', 'description': '', 'image': 'HOUSE0'},
    {'name': 'AWS',              'color': 'gray',       'price': 180, 'type': 'property', 'fee': [18, 54, 108, 162]},
    {'name': 'Azure',            'color': 'gray',       'price': 180, 'type': 'property', 'fee': [18, 54, 108, 162]},
]
