CARDS = {
    0: {'name': 'Start',            'color': '#F7F7F7',     'price': 0,     'special': True},
    1: {'name': 'Zolte 1',          'color': 'yellow',      'price': 260,   'special': False},
    2: {'name': None,               'color': '#F7F7F7',     'price': 0,     'special': True},
    3: {'name': 'Zolte 2',          'color': 'yellow',      'price': 260,   'special': False},
    4: {'name': None,               'color': '#F7F7F7',     'price': 0,     'special': True},
    5: {'name': 'Niebieskie 1',     'color': 'blue',        'price': 400,   'special': False},
    6: {'name': None,               'color': '#F7F7F7',     'price': 0,     'special': True},
    7: {'name': 'Niebieskie 2',     'color': 'blue',        'price': 400,   'special': False},
    8: {'name': 'Niebieskie 3',     'color': 'blue',        'price': 400,   'special': False},
    9: {'name': '9',                'color': '#F7F7F7',     'price': 0,     'special': True},
    10: {'name': 'Różowe 1',        'color': 'pink',        'price': 160,   'special': False},
    11: {'name': 'Różowe 1',        'color': 'pink',        'price': 160,   'special': False},
    12: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    13: {'name': 'Różowe 3',        'color': 'pink',        'price': 160,   'special': False},
    14: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    15: {'name': 'Pomarańczowe 1',  'color': 'orange',      'price': 200,   'special': False},
    16: {'name': 'Pomarańczowe 2',  'color': 'orange',      'price': 200,   'special': False},
    17: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    18: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    19: {'name': 'Zielone 1',       'color': 'lightgreen',  'price': 340,   'special': False},
    20: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    21: {'name': 'Zielone 2',       'color': 'lightgreen',  'price': 340,   'special': False},
    22: {'name': 'Zielone 3',       'color': 'lightgreen',  'price': 340,   'special': False},
    23: {'name': 'Fioletowe 1',     'color': 'purple',      'price': 140,   'special': False},
    24: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    25: {'name': 'Fioletowe 2',     'color': 'purple',      'price': 140,   'special': False},
    26: {'name': 'Fioletowe 3',     'color': 'purple',      'price': 140,   'special': False},
    27: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    28: {'name': 'Brązowe 1',       'color': 'brown',       'price': 100,   'special': False},
    29: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    30: {'name': 'Brązowe 2',       'color': 'brown',       'price': 100,   'special': False},
    31: {'name': 'Brązowe 3',       'color': 'brown',       'price': 100,   'special': False},
    32: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    33: {'name': None,              'color': '#F7F7F7',     'price': 0,     'special': True},
    34: {'name': 'Szare 1',         'color': 'gray',        'price': 180,   'special': False},
    35: {'name': 'Szare 2',         'color': 'gray',        'price': 180,   'special': False},
}
