CARDS = [
    {'name': 'Start',            'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Zolte 1',          'color': 'yellow',     'price': 260, 'type': 'property', 'fee': [26, 78, 156, 234]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Zolte 2',          'color': 'yellow',     'price': 260, 'type': 'property', 'fee': [26, 78, 156, 234]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Niebieskie 1',     'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Niebieskie 2',     'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': 'Niebieskie 3',     'color': 'blue',       'price': 400, 'type': 'property', 'fee': [40, 120, 240, 360]},
    {'name': '9',                'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Różowe 1',         'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': 'Różowe 1',         'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Różowe 3',         'color': 'pink',       'price': 160, 'type': 'property', 'fee': [16, 48, 96, 144]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Pomarańczowe 1',   'color': 'orange',     'price': 200, 'type': 'property', 'fee': [20, 60, 120, 180]},
    {'name': 'Pomarańczowe 2',   'color': 'orange',     'price': 200, 'type': 'property', 'fee': [20, 60, 120, 180]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Zielone 1',        'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Zielone 2',        'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': 'Zielone 3',        'color': 'lightgreen', 'price': 340, 'type': 'property', 'fee': [34, 102, 204, 306]},
    {'name': 'Fioletowe 1',      'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Fioletowe 2',      'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': 'Fioletowe 3',      'color': 'purple',     'price': 140, 'type': 'property', 'fee': [14, 42, 84, 126]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Brązowe 1',        'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Brązowe 2',        'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': 'Brązowe 3',        'color': 'brown',      'price': 100, 'type': 'property', 'fee': [10, 30, 60, 90]},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': None,               'color': '#F7F7F7',    'price': 0,   'type': 'special'},
    {'name': 'Szare 1',          'color': 'gray',       'price': 180, 'type': 'property', 'fee': [18, 54, 108, 162]},
    {'name': 'Szare 2',          'color': 'gray',       'price': 180, 'type': 'property', 'fee': [18, 54, 108, 162]},
]
